Week 5, Assignment C1:

Logistic Regression with Yahoo! Finance API in Python

In this notebook, we will study Logistic Regression using the Yahoo! Finance API in Python.

Please complete the lines bellow where you see "#TODO".

In [17]:
#Objective 1.
#Use this cell to import the Numpy (as np), Pandas (as pd), and YFinance (as yf) packages.

import numpy as np
import pandas as pd
import yfinance as yf


#Our work will also require some components of the Sklearn and Pandas_Datareader packages as imported below:

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from pandas_datareader import data as pdr
yf.pdr_override()

In [18]:
#Objective 2.
#Select a stock symbol for a stock whose historical data is available on the Yahoo! Finance website.  Store the
#string of your chosen symbol to the new variable "stock_symbol".

stock_symbol = '2020.SR'

In [19]:
#Objective 3.
#Use the function "pdr.get_data_yahoo(stock_symbol, start_date, end_date)" to generate a Pandas dataframe of
#historical stock data for your chosen stock.  Retain only the first four columns of the dataframe.  Be sure to 
#drop any rows containing NaN's, and take a peek at the resulting dataframe to make sure everything looks good.

df = pdr.get_data_yahoo(stock_symbol, '2000-11-08', '2021-11-08' )
#TODO
df = df.iloc[:, :4]
#TODO
df = df.dropna()
df

[*********************100%***********************]  1 of 1 completed


Open        High         Low       Close
Date                                                      
2010-03-04   87.450218   88.200218   86.400215   87.300217
2010-03-07   87.900223   89.250221   87.600220   87.900223
2010-03-08   87.900223   88.650223   87.300217   88.200218
2010-03-09   88.350220   88.500221   87.900223   87.900223
2010-03-10   87.900223   88.200218   87.600220   87.600220
...                ...         ...         ...         ...
2021-11-01  162.399994  166.000000  162.199997  164.800003
2021-11-02  164.800003  166.399994  163.600006  165.000000
2021-11-03  165.000000  167.399994  163.399994  165.800003
2021-11-04  165.399994  167.199997  164.000000  167.000000
2021-11-07  169.000000  169.000000  166.600006  168.600006

[2851 rows x 4 columns]

In [20]:
#Objective 4.
#Use the historical data to define some predictor variables.  Add these variables to the dataframe.  Include, at a
#minimum, (Predictor.I) the rolling average closing price over the past fifteen (15) days and (Predictor.II) the
#change in opening price over the past one (1) day.  Be sure to again drop any rows containing NaN's, and take a
#peek at the resulting dataframe to make sure everything looks good.  Store the dataframe as the new variable "X".

df['Close_15_Rolling'] = df['Close'].rolling(window=15).mean()
#TODO
df['Open_1_Change'] = df['Open']-df['Open'].shift(1)

#TODO
df = df.dropna()
#TODO
X = df
#TODO
X

Open        High         Low       Close  Close_15_Rolling  \
Date                                                                           
2010-03-24   85.800217   87.450218   85.800217   86.700218         87.760219   
2010-03-25   87.450218   87.450218   86.100212   87.000214         87.740219   
2010-03-28   87.300217   87.450218   86.550217   87.000214         87.680219   
2010-03-29   87.000214   87.000214   87.000214   87.000214         87.600218   
2010-03-30   87.000214   87.000214   87.000214   87.000214         87.540218   
...                ...         ...         ...         ...               ...   
2021-11-01  162.399994  166.000000  162.199997  164.800003        171.760001   
2021-11-02  164.800003  166.399994  163.600006  165.000000        171.226667   
2021-11-03  165.000000  167.399994  163.399994  165.800003        170.640000   
2021-11-04  165.399994  167.199997  164.000000  167.000000        170.120000   
2021-11-07  169.000000  169.000000  166.600006  168.600006        169.826667   

            Open_1_Change  
Date                       
2010-03-24      -0.449997  
2010-03-25       1.650002  
2010-03-28      -0.150002  
2010-03-29      -0.300003  
2010-03-30       0.000000  
...                   ...  
2021-11-01      -1.400009  
2021-11-02       2.400009  
2021-11-03       0.199997  
2021-11-04       0.399994  
2021-11-07       3.600006  

[2837 rows x 6 columns]

In [21]:
#Objective 5.
#Define the target or dependent variable to be one (1) if the change in closing price over the past one (1) day is
#nonnegative and negative one (-1) if the change in closing price over the past one (1) day is negative.  This
#variable's values should be forward-looking (i.e., you should subtract today's price from tomorrow's price rather
#than subtracting yesterday's price from today's price).  Store the resulting values as the new variable "y".  You
#may find the "np.where(*args)" function to be useful.  Look it up in Numpy documentation for support.

y = np.where(df['Close'].shift(-1) - df['Close'] < 0, -1, 1)
y
#TODO

array([1, 1, 1, ..., 1, 1, 1])

In [22]:
#Objective 6.
#Split the data into training and test sets, putting the first seventy percent (70%) of the data in the training
#set.

index = int(0.7*len(X))
X_train, X_test, y_train, y_test = X[:index], X[index:], y[:index], y[index:]
#TODO

In [23]:
X_train

Open       High        Low      Close  Close_15_Rolling  \
Date                                                                       
2010-03-24  85.800217  87.450218  85.800217  86.700218         87.760219   
2010-03-25  87.450218  87.450218  86.100212  87.000214         87.740219   
2010-03-28  87.300217  87.450218  86.550217  87.000214         87.680219   
2010-03-29  87.000214  87.000214  87.000214  87.000214         87.600218   
2010-03-30  87.000214  87.000214  87.000214  87.000214         87.540218   
...               ...        ...        ...        ...               ...   
2018-06-24  61.000000  61.700001  60.900002  61.400002         60.826667   
2018-06-25  61.500000  61.799999  61.099998  61.799999         60.800000   
2018-06-26  61.799999  62.500000  61.299999  62.099998         60.793333   
2018-06-27  62.400002  62.500000  62.000000  62.099998         60.866666   
2018-06-28  62.200001  62.200001  61.400002  61.700001         60.886666   

            Open_1_Change  
Date                       
2010-03-24      -0.449997  
2010-03-25       1.650002  
2010-03-28      -0.150002  
2010-03-29      -0.300003  
2010-03-30       0.000000  
...                   ...  
2018-06-24       0.599998  
2018-06-25       0.500000  
2018-06-26       0.299999  
2018-06-27       0.600002  
2018-06-28      -0.200001  

[1985 rows x 6 columns]

In [24]:
X_test

Open        High         Low       Close  Close_15_Rolling  \
Date                                                                           
2018-07-01   61.599998   61.900002   60.500000   61.099998         60.886666   
2018-07-02   61.099998   61.400002   60.799999   61.200001         60.933333   
2018-07-03   61.000000   61.000000   60.700001   60.900002         60.973333   
2018-07-04   60.799999   61.299999   60.700001   61.200001         61.033333   
2018-07-05   61.299999   61.599998   61.099998   61.299999         61.100000   
...                ...         ...         ...         ...               ...   
2021-11-01  162.399994  166.000000  162.199997  164.800003        171.760001   
2021-11-02  164.800003  166.399994  163.600006  165.000000        171.226667   
2021-11-03  165.000000  167.399994  163.399994  165.800003        170.640000   
2021-11-04  165.399994  167.199997  164.000000  167.000000        170.120000   
2021-11-07  169.000000  169.000000  166.600006  168.600006        169.826667   

            Open_1_Change  
Date                       
2018-07-01      -0.600002  
2018-07-02      -0.500000  
2018-07-03      -0.099998  
2018-07-04      -0.200001  
2018-07-05       0.500000  
...                   ...  
2021-11-01      -1.400009  
2021-11-02       2.400009  
2021-11-03       0.199997  
2021-11-04       0.399994  
2021-11-07       3.600006  

[852 rows x 6 columns]

In [25]:
y_train

array([ 1,  1,  1, ...,  1, -1, -1])

In [26]:
y_test

array([ 1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  1, -1,
       -1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,
       -1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,
        1, -1, -1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1,  1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1, -1,
        1,  1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1,
       -1,  1, -1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1,
       -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  1, -1, -1, -1,
        1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1,
        1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1,
        1, -1,  1, -1, -1,  1,  1, -1,  1,  1,  1, -1,  1, -1, -1, -1, -1,
       -1,  1, -1, -1, -1

In [27]:
#Objective 7.
#Instantiate the Logistic Regression model object, and use its ".fit(*args)" method to fit the model to the 
#training data.

logistic = LogisticRegression()
logistic = logistic.fit(X_train, y_train)
#TODO

In [28]:
#Objective 8.
#Examine the model's coefficients by using its ".coef_" method.

pd.DataFrame(zip(X.columns, np.transpose(logistic.coef_)))

0                       1
0              Open  [-0.43344213599653597]
1              High   [0.21097393712363255]
2               Low   [0.40745731546817965]
3             Close  [-0.23069083337082918]
4  Close_15_Rolling   [0.04756440797097025]
5     Open_1_Change  [0.015361294596220905]

In [29]:
#Objective 9.
#Use the model's ".predict_proba(*args)" and ".predict(*args)" methods to generate predictions over the test set.

probabilities = logistic.predict_proba(X_test) #TODO
predictions = logistic.predict(X_test)
#TODO

In [30]:
#Objective 10.
#Use the function "metrics.confusion_matrix(*args)" to create a confusion matrix comparing the predicted and true
#classification labels over the test set.
metrics.confusion_matrix(y_test, predictions)
#TODO

array([[ 86, 292],
       [ 70, 404]], dtype=int64)

In [31]:
#Objective 11.
#Calculate the model's accuracy on the test set using its ".score(*args)" method.
logistic.score(X_test, y_test)
#TODO

0.5751173708920188

In [37]:
#Objective 12.
#Use five-fold cross validation to cross-check the accuracy of the model over different held-out test sets.  This
#is where you should use the function "cross_val_score(*args)".

cross_val = cross_val_score(logistic,X,y,cv=5)
#cross_val = cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=5)
#cross_val = cross_val_score(logistic,X_test,y_test,cv=5)
#cross_val = cross_val_score(logistic, X, y, scoring='accuracy', cv = 5)
cross_val
#TODO

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.56690141, 0.58098592, 0.55555556, 0.5696649 , 0.59259259])